name: DeployEC2

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, The deployment in EC2 has started!
    - name: Run a multi-line script
      env: # Secrets sent as environment variables
        EC2: ${{ secrets.EC2 }}
        TRAVIS_CI_SECRET: ${{ secrets.TRAVIS_CI_SECRET }}
      run: |
        openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./deploy/.secret -out ./try.arrow-kt.pem -d -a -nopad
        chmod 400 ./try.arrow-kt.pem
        ssh -o "StrictHostKeyChecking no" -q -i ./try.arrow-kt.pem $EC2 'cd try.arrow-kt.io; sh deploy.sh; exit'
